# Generated by Django 3.2.5 on 2021-08-03 07:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyschedule',
            name='date',
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='resourcebooking',
            name='booked_for',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='resourcebooking',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcebooking',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourcebooking',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resourcebooking',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourcebooking',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.resource'),
        ),
        migrations.AddField(
            model_name='resourcebooking',
            name='total_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resourcebooking',
            name='total_number_of_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
