# Generated by Django 3.2.5 on 2021-08-03 08:00

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210803_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyschedule',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='dailyschedule',
            name='created',
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='date',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcebooking',
            name='booking_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='resourcebooking',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
